### ISSUE TITLE
Nieprawidłowa weryfikacja nazwisk

### ISSUE THREAD

**Issue by MonichSC** [MonichSC/ZPI-bugtracker#12]
Jeżeli pierwsza litera nazwiska jest znakiem polskim, backend odmawia przyjęcia takiego użytkownika

**Comment by Palum12** [comment]
![cr7ms_owcaa7hzt](https://user-images.githubusercontent.com/16270898/42024551-be896fda-7ac2-11e8-82ef-482f0d799ffe.jpg)

**Comment by Palum12** [comment]
a tak serio to proszę o podanie jakiegoś nazwiska które nie przechodzi ? bo jak patrzę to jest trochę obsługa sensownych liter
