### ISSUE TITLE
Logowanie - puste dane

### ISSUE THREAD

**Issue by MonichSC** [MonichSC/ZPI-bugtracker#4]
Podczas logowania się, pozostawienie któregos z pól pustego i naciśniecie ENTER powoduje przeniesienie użytkownika na stronę główną.

Zachowanie aplikacji podczas naciskania ENTER i kliknięciem w przycisk Zaloguj się powinno byc takie samo

**Comment by maaaaagda** [comment]
fixed

**Comment by MonichSC** [comment]
Merged into develop: PR31
