### ISSUE TITLE
Błąd polskich znaków w mailu

### ISSUE THREAD

**Issue by maaaaagda** [MonichSC/ZPI-bugtracker#7]
![image](https://user-images.githubusercontent.com/17687646/41296794-0053517c-6e5e-11e8-994f-dca31d555e2e.png)

**Comment by Palum12** [comment]
przepisałem treść na windowsie z innym kodowaniem, nie wiem jak to będzie teraz wyglądać na linuchu ale biorąc pod uwagę, że 99% osób używa windowsa to może być jako tymczasowe rozwiązanie
